"use client";

import type { CompanyBundle } from "@/types";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { OverviewTab } from "@/features/company-overview/overview-tab";
import { FinancialsTab } from "@/features/financials/financials-tab";
import { ValuationTab } from "@/features/valuation/valuation-tab";
import { MATab } from "@/features/ma-analysis/ma-tab";
import { MemoTab } from "@/features/memo/memo-tab";

export function CompanyDashboard({ bundle }: { bundle: CompanyBundle }) {
  return (
    <main className="min-h-screen bg-paper pb-24">
      <div className="mx-auto max-w-6xl px-6">
        <Tabs defaultValue="overview" className="pt-2">
          <TabsList>
            <TabsTrigger value="overview">Overview</TabsTrigger>
            <TabsTrigger value="financials">Financials</TabsTrigger>
            <TabsTrigger value="valuation">Valuation</TabsTrigger>
            <TabsTrigger value="ma">M&amp;A</TabsTrigger>
            <TabsTrigger value="memo">Memo</TabsTrigger>
          </TabsList>

          <TabsContent value="overview" className="py-8">
            <OverviewTab bundle={bundle} />
          </TabsContent>
          <TabsContent value="financials" className="py-8">
            <FinancialsTab bundle={bundle} />
          </TabsContent>
          <TabsContent value="valuation" className="py-8">
            <ValuationTab bundle={bundle} />
          </TabsContent>
          <TabsContent value="ma" className="py-8">
            <MATab bundle={bundle} />
          </TabsContent>
          <TabsContent value="memo" className="py-8">
            <MemoTab bundle={bundle} />
          </TabsContent>
        </Tabs>
      </div>

      <footer className="mx-auto mt-8 max-w-6xl px-6">
        <p className="max-w-2xl text-2xs leading-relaxed text-ink-faint">
          DealLab is an analytical and educational platform. Information
          generated by the platform does not constitute investment advice.
        </p>
      </footer>
    </main>
  );
}
