import type {
  AIAnalystOutput,
  BalanceSheet,
  CompanyBundle,
  Company,
  DCFAssumptions,
  FinancialStatement,
  MAScoreBreakdown,
  PeerCompany,
  ValuationMetrics,
} from "@/types";
import { computeMAScore } from "@/lib/calculations/ma-score";

/**
 * DEMO DATA — Ferrari N.V. (RACE)
 * --------------------------------
 * Figures below are illustrative approximations for product-demo purposes
 * only. They are NOT sourced from a live financial data feed and must not
 * be treated as Ferrari's actual reported results. Every value carries
 * `source: "DEMO DATA"` at the object level so the UI can badge it clearly.
 *
 * `strategicPositioning` and `consolidationPotential` below are explicit
 * analyst judgment inputs to the M&A score (see lib/calculations/ma-score.ts)
 * — they are curated here, not generated by the LLM at request time.
 */

const company: Company = {
  id: "race",
  ticker: "RACE",
  name: "Ferrari N.V.",
  exchange: "NYSE / EURONEXT MILAN",
  country: "Italy / Netherlands (incorporated)",
  sector: "Consumer Discretionary",
  industry: "Luxury Performance Automobiles",
  description:
    "Ferrari designs, engineers, and manufactures luxury performance sports cars, and licenses its brand across lifestyle, hospitality, and entertainment categories. The company operates a deliberately supply-constrained production model that supports premium pricing, extremely high order backlogs, and industry-leading margins relative to both mass-market and other luxury automakers.",
  currency: "EUR",
  sharePrice: 450.0,
  dilutedSharesOutstanding: 178.5,
  marketCap: 80325,
  source: "DEMO DATA",
};

const financials: FinancialStatement[] = [
  {
    companyId: "race",
    year: 2022,
    period: "actual",
    revenue: 5099,
    revenueGrowth: null,
    ebitda: 1897,
    ebitdaMargin: 0.372,
    ebit: 1296,
    ebitMargin: 0.254,
    netIncome: 939,
    eps: 5.16,
    depreciationAmortization: 601,
    capex: 700,
    changeInNetWorkingCapital: 40,
    freeCashFlow: 900,
  },
  {
    companyId: "race",
    year: 2023,
    period: "actual",
    revenue: 5972,
    revenueGrowth: 0.171,
    ebitda: 2299,
    ebitdaMargin: 0.385,
    ebit: 1646,
    ebitMargin: 0.276,
    netIncome: 1252,
    eps: 6.99,
    depreciationAmortization: 653,
    capex: 780,
    changeInNetWorkingCapital: 35,
    freeCashFlow: 1050,
  },
  {
    companyId: "race",
    year: 2024,
    period: "actual",
    revenue: 6675,
    revenueGrowth: 0.118,
    ebitda: 2569,
    ebitdaMargin: 0.385,
    ebit: 1900,
    ebitMargin: 0.285,
    netIncome: 1526,
    eps: 8.53,
    depreciationAmortization: 669,
    capex: 850,
    changeInNetWorkingCapital: 30,
    freeCashFlow: 1200,
  },
  {
    companyId: "race",
    year: 2025,
    period: "actual",
    revenue: 7150,
    revenueGrowth: 0.071,
    ebitda: 2760,
    ebitdaMargin: 0.386,
    ebit: 2040,
    ebitMargin: 0.285,
    netIncome: 1610,
    eps: 9.05,
    depreciationAmortization: 720,
    capex: 900,
    changeInNetWorkingCapital: 25,
    freeCashFlow: 1300,
  },
  {
    companyId: "race",
    year: 2026,
    period: "actual",
    revenue: 7550,
    revenueGrowth: 0.056,
    ebitda: 2940,
    ebitdaMargin: 0.389,
    ebit: 2185,
    ebitMargin: 0.289,
    netIncome: 1700,
    eps: 9.65,
    depreciationAmortization: 755,
    capex: 950,
    changeInNetWorkingCapital: 20,
    freeCashFlow: 1400,
  },
];

const balanceSheet: BalanceSheet[] = [
  { companyId: "race", year: 2022, cash: 1400, totalDebt: 3000, netDebt: 1600, totalAssets: 9000, totalEquity: 3200 },
  { companyId: "race", year: 2023, cash: 1600, totalDebt: 3100, netDebt: 1500, totalAssets: 9800, totalEquity: 3700 },
  { companyId: "race", year: 2024, cash: 1750, totalDebt: 3150, netDebt: 1400, totalAssets: 10500, totalEquity: 4200 },
  { companyId: "race", year: 2025, cash: 1900, totalDebt: 3200, netDebt: 1300, totalAssets: 11200, totalEquity: 4700 },
  { companyId: "race", year: 2026, cash: 2050, totalDebt: 3250, netDebt: 1200, totalAssets: 11900, totalEquity: 5200 },
];

// Illustrative share price path used only to back into historical EV/EBITDA
// trend lines for the "historical average" column in the valuation module.
const historicalSharePrice: Record<number, number> = {
  2022: 210,
  2023: 280,
  2024: 350,
  2025: 400,
  2026: 450,
};

const valuation: ValuationMetrics[] = financials.map((f) => {
  const bs = balanceSheet.find((b) => b.year === f.year)!;
  const price = historicalSharePrice[f.year];
  const marketCap = price * company.dilutedSharesOutstanding;
  const enterpriseValue = marketCap + bs.netDebt;
  return {
    companyId: "race",
    year: f.year,
    enterpriseValue,
    marketCap,
    evRevenue: enterpriseValue / f.revenue,
    evEbitda: enterpriseValue / f.ebitda,
    evEbit: enterpriseValue / f.ebit,
    pe: marketCap / f.netIncome,
    fcfYield: f.freeCashFlow / marketCap,
  };
});

const peers: PeerCompany[] = [
  {
    id: "mc-lvmh",
    ticker: "MC.PA",
    name: "LVMH Moët Hennessy Louis Vuitton",
    marketCap: 350000,
    enterpriseValue: 370000,
    revenue: 86000,
    ebitda: 22000,
    ebitdaMargin: 0.256,
    revenueGrowth: 0.03,
    evRevenue: 4.3,
    evEbitda: 16.8,
    pe: 24.0,
    source: "DEMO DATA",
  },
  {
    id: "rms-hermes",
    ticker: "RMS.PA",
    name: "Hermès International",
    marketCap: 230000,
    enterpriseValue: 225000,
    revenue: 15000,
    ebitda: 6500,
    ebitdaMargin: 0.433,
    revenueGrowth: 0.12,
    evRevenue: 15.0,
    evEbitda: 34.6,
    pe: 55.0,
    source: "DEMO DATA",
  },
  {
    id: "ker-kering",
    ticker: "KER.PA",
    name: "Kering",
    marketCap: 30000,
    enterpriseValue: 38000,
    revenue: 17000,
    ebitda: 3500,
    ebitdaMargin: 0.206,
    revenueGrowth: -0.08,
    evRevenue: 2.2,
    evEbitda: 10.9,
    pe: 14.0,
    source: "DEMO DATA",
  },
  {
    id: "mo-l-moncler",
    ticker: "MONC.MI",
    name: "Moncler",
    marketCap: 16000,
    enterpriseValue: 15200,
    revenue: 3100,
    ebitda: 1050,
    ebitdaMargin: 0.339,
    revenueGrowth: 0.06,
    evRevenue: 4.9,
    evEbitda: 14.5,
    pe: 22.0,
    source: "DEMO DATA",
  },
  {
    id: "p911-porsche",
    ticker: "P911.DE",
    name: "Porsche AG",
    marketCap: 45000,
    enterpriseValue: 58000,
    revenue: 40000,
    ebitda: 7200,
    ebitdaMargin: 0.18,
    revenueGrowth: 0.02,
    evRevenue: 1.45,
    evEbitda: 8.1,
    pe: 11.0,
    source: "DEMO DATA",
  },
];

const dcfDefaults: DCFAssumptions = {
  years: [2027, 2028, 2029, 2030, 2031],
  revenueGrowth: [0.08, 0.07, 0.065, 0.06, 0.055],
  ebitdaMargin: [0.395, 0.398, 0.4, 0.402, 0.405],
  daPctRevenue: [0.1, 0.1, 0.1, 0.1, 0.1],
  capexPctRevenue: [0.125, 0.125, 0.12, 0.12, 0.115],
  nwcPctRevenue: [0.01, 0.01, 0.01, 0.01, 0.01],
  taxRate: 0.24,
  wacc: 0.075,
  terminalGrowth: 0.025,
  baseRevenue: 7550,
};

const analystAnalysis: AIAnalystOutput = {
  summary:
    "Ferrari combines industry-leading profitability with a deliberately constrained production model, giving it pricing power and order-book visibility unusual for an automaker. The stock trades at a substantial premium to both auto and broader luxury peers, reflecting scarcity value and brand equity rather than a typical cyclical profile.",
  investment_highlights: [
    "Structural scarcity: production is order-book (not demand) constrained, supporting multi-year revenue visibility.",
    "Best-in-class profitability: EBITDA margin near 39%, well above both mass-market and luxury-goods peers.",
    "Diversified revenue beyond cars: personalization, licensing, and Corse Clienti racing programs carry very high incremental margin.",
    "Disciplined balance sheet: Net Debt / EBITDA around 0.4x, providing flexibility for electrification and capacity investment.",
    "Multi-year new-model cadence, including the phased hybrid and BEV rollout, supports the growth algorithm without volume expansion.",
  ],
  risks: [
    {
      label: "Acquisition premium already priced in",
      level: "High",
      note: "Ferrari trades well above luxury and auto peer multiples, leaving little room for a strategic buyer to pay a further premium and still clear a normal return hurdle.",
    },
    {
      label: "Concentrated, structurally protective ownership",
      level: "High",
      note: "Exor and the Ferrari family hold controlling economic and voting positions via a loyalty-voting structure, making an unsolicited change of control highly improbable regardless of financial attractiveness.",
    },
    {
      label: "Regulatory / antitrust exposure",
      level: "Low",
      note: "Ferrari's narrow production volumes make competition-authority objections unlikely versus a mass-market automotive combination.",
    },
    {
      label: "Model-cycle and electrification execution risk",
      level: "Medium",
      note: "Margin durability depends on successfully extending brand equity and pricing power into hybrid and BEV models.",
    },
    {
      label: "Macro / discretionary demand cyclicality",
      level: "Medium",
      note: "Ultra-high-net-worth demand has historically been more resilient than mass luxury, but is not immune to a severe global downturn.",
    },
    {
      label: "Key-person / management dependency",
      level: "Low",
      note: "Leadership succession has been managed deliberately, with institutionalized design and engineering processes reducing single-person dependency.",
    },
  ],
  ma_rationale: [
    "Brand and IP acquisition: Ferrari's marque carries licensing value across categories well beyond automobiles.",
    "Technology and motorsport IP: Formula 1 and hypercar programs generate transferable powertrain and materials engineering value.",
    "Portfolio anchor for a luxury conglomerate seeking an automotive/mobility trophy asset.",
    "Vertical or horizontal integration for an adjacent performance-mobility or luxury goods platform.",
  ],
  buyer_types: [
    {
      category: "Global strategic competitor",
      rationale:
        "A large luxury-goods conglomerate could seek Ferrari as a trophy brand extension into automotive lifestyle, though scale and price would be extraordinary.",
    },
    {
      category: "Adjacent industry player",
      rationale:
        "A premium mobility or motorsport-adjacent technology company could value Ferrari's engineering IP and brand halo.",
    },
    {
      category: "Sovereign wealth fund",
      rationale:
        "Sovereign investors have shown appetite for trophy sports and luxury assets, though a controlling stake is not realistically available given the current ownership structure.",
    },
    {
      category: "Family office / long-term holder",
      rationale:
        "Ferrari's current controlling shareholders (Exor, the Ferrari family) are themselves the most probable long-term holders — this category is included for completeness, not as a transaction scenario.",
    },
  ],
  bull_case:
    "Continued mix-shift toward higher-priced special series and personalization, successful hybrid/BEV launches that preserve pricing power, and disciplined capacity growth drive EBITDA margin toward the low 40s% with high-single-digit revenue growth, supporting further multiple resilience.",
  bear_case:
    "A sharper-than-expected slowdown in ultra-high-net-worth discretionary spending, weaker reception of electrified models, or margin dilution from higher input and R&D costs compress both earnings growth and the valuation multiple simultaneously.",
  conclusion:
    "Ferrari screens as a high-quality, structurally advantaged business, but the M&A framework below should be read as an analytical lens, not a prediction: the combination of premium valuation and a protective, concentrated ownership structure makes a change-of-control transaction unlikely in the near term.",
};

// Analyst judgment inputs, curated explicitly and separately from the
// quantitative sub-scores computed inside computeMAScore().
const strategicPositioning = 90; // dominant brand / structural scarcity moat
const consolidationPotential = 22; // low: concentrated protective ownership, thin auto/luxury M&A precedent at this scale

function buildMAScore(): MAScoreBreakdown {
  const latestFinancials = financials[financials.length - 1];
  const latestBalanceSheet = balanceSheet[balanceSheet.length - 1];
  const latestValuation = valuation[valuation.length - 1];
  return computeMAScore({
    latestFinancials,
    latestBalanceSheet,
    peers,
    targetEvEbitda: latestValuation.evEbitda,
    strategicPositioning,
    consolidationPotential,
  });
}

export const ferrariBundle: CompanyBundle = {
  company,
  financials,
  balanceSheet,
  valuation,
  peers,
  dcfDefaults,
  analystAnalysis,
  maScore: buildMAScore(),
};
