export const GLOSSARY: Record<string, string> = {
  "Enterprise Value":
    "The theoretical value of a company's core operating assets, independent of capital structure. EV = Equity Value + Total Debt − Cash.",
  "Equity Value":
    "The value attributable to shareholders. Equity Value = Enterprise Value − Net Debt.",
  "EV / EBITDA":
    "Enterprise Value divided by EBITDA. The most common trading and transaction multiple because it's capital-structure and non-cash-charge neutral.",
  "EV / Revenue":
    "Enterprise Value divided by revenue. Useful when EBITDA is negative or margins vary widely across peers.",
  WACC: "Weighted Average Cost of Capital — the blended required return of a company's debt and equity holders, used to discount future cash flows to present value.",
  "Terminal Value":
    "The value of all cash flows beyond the explicit forecast period, capitalized in a single figure using the Gordon Growth formula: FCF × (1+g) / (WACC − g).",
  "Net Debt":
    "Total debt minus cash and cash equivalents. Represents the debt a buyer would effectively assume net of the cash it acquires.",
  "Net Debt / EBITDA":
    "A leverage ratio showing how many years of EBITDA it would take to repay net debt. Lower is generally viewed as more conservative.",
  "Free Cash Flow":
    "Cash generated by the business after capital expenditure, available to all capital providers (debt and equity).",
  "Unlevered Free Cash Flow":
    "Free cash flow before the effect of financing decisions — NOPAT + D&A − Capex − ΔNWC. The cash flow discounted in a DCF.",
  "P/E":
    "Price-to-Earnings ratio: market capitalization divided by net income. An equity-value multiple, unlike EV multiples which are capital-structure neutral.",
  "FCF Yield":
    "Free cash flow divided by market capitalization — the cash return an equity holder is theoretically buying at the current price.",
  "Accretion / Dilution":
    "In an M&A context, whether a transaction increases (accretive) or decreases (dilutive) the acquirer's pro forma earnings per share.",
};
